version: "3"
volumes:
  nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.10,rw
      device: ":/volume2"
services:
  sonarr:
    image: lsioarmhf/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
      - "32001:32001"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Zurich
    volumes:
      - /home/pi/.config/NzbDrone:/config
      - nfs:/volume2
  radarr:
    image: lsioarmhf/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Zurich
    volumes:
      - /home/pi/radarr/config:/config
      - nfs:/volume2
  jackett:
    image: lsioarmhf/jackett
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Zurich
    volumes:
      - /home/pi/jackett/config:/config
      - nfs:/volume2
